version: "3"
services:
  app:
    image: ghcr.io/fabrizioferroni/app-test-ga:latest
    ports:
      - 8080:80
    restart: always
    volumes:
      - /public:/usr/share/nginx/html/public
    networks:
      - frontend

networks:
  frontend:
