version: "3"
services:
  app:
    image: fabriziodevar/app-test-ga:latest
    ports:
      - 8080:80
    restart: always
    volumes:
      - /public:/var/www/html/public
    networks:
      - frontend

networks:
  frontend:
    driver: bridge
