version: "3"
services:
  app:
    image: fabriziodevar/app-test-ga:latest
    ports:
      - 8080:80
    restart: always
    volumes:
      - /public:/usr/share/nginx/html/public
    command: sh -c "mv /usr/share/nginx/html/img/* /usr/share/nginx/html/public/img/ && mv /usr/share/nginx/html/js/* /usr/share/nginx/html/public/js/"
    networks:
      - frontend

networks:
  frontend:
    driver: bridge
