version: "3"
services:
  web:
    container_name: app_test_ga
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./public:/usr/share/nginx/html/public
