version: "3"
services:
  app:
    image: nginx:1.25-alpine
    ports:
      - 10000:80
    restart: always
    volumes:
      - ./public:/usr/share/nginx/html/public
    networks:
      - frontend

networks:
  frontend:
