name: Deploy to portainer

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    name: Deploy to portainer
    runs-on: ubuntu-latest
    timeout-minutes: 20

    env:
      GITHUB_REF: ${{ github.ref }}
      DOCKER_REGISTRY: ghcr.io
      DOCKER_IMAGE: fabrizioferroni/app-test-ga

    steps:
      - uses: actions/checkout@v2

      - name: Creating envs
        run: |
          echo "IMAGE_TAG=sha-$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          echo "DOCKER_IMAGE_URI=${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE }}" >> $GITHUB_ENV

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build docker image and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.DOCKER_IMAGE_URI }}:${{ env.IMAGE_TAG }},${{ env.DOCKER_IMAGE_URI }}:latest

      - name: Sleep for 10 seconds
        run: sleep 10s
        shell: bash

      - name: Deploy stack to Portainer
        uses: rrennoir/portainer-stack@v2
        with:
          portainerUrl: ${{ secrets.PORTAINER_HOST }}
          portainerApiKey: ${{ secrets.PORTAINER_ACCES_TOKEN }}
          portainerEndpointId: 2
          stackName: "app-test-ga"
          stackType: 2
          composeFile: docker-compose.yml
          delete: false
          prune: false
          pullImage: false
          verifySSL: false

      - name: Update compose file
        run: sed -i 's|nginx:latest|${{ env.DOCKER_IMAGE_URI }}:${{ env.IMAGE_TAG }},${{ env.DOCKER_IMAGE_URI }}:latest|g' docker-compose.yml

        # Create / update with prune and pull image
      - name: Deploy stack to Portainer new img
        uses: rrennoir/portainer-stack@main
        with:
          portainerUrl: ${{ secrets.PORTAINER_HOST }}
          portainerApiKey: ${{ secrets.PORTAINER_ACCES_TOKEN }}
          portainerEndpointId: 2
          stackName: "app-test-ga"
          stackType: 2
          composeFile: docker-compose.yml
          prune: true
          pullImage: true
          verifySSL: false

      - name: Deploy stack to Portainer delete img
        uses: rrennoir/portainer-stack@main
        with:
          portainerUrl: ${{ secrets.PORTAINER_HOST }}
          portainerApiKey: ${{ secrets.PORTAINER_ACCES_TOKEN }}
          portainerEndpointId: 2
          stackName: "app-test-ga"
          stackType: 2
          composeFile: docker-compose.yml
          delete: true
          verifySSL: false
