name: Test action
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Create / update
      - uses: rrennoir/portainer-stack@main
        with:
          portainerUrl: ${{ secrets.PORTAINER_HOST}}
          portainerApiKey: ${{ secrets.PORTAINER_ACCESS_TOKEN }}
          portainerEndpointId: 2
          stackName: "app-test-ga"
          stackType: 2
          composeFile: stack-definition.yml
          delete: false
          prune: false
          pullImage: false
          verifySSL: false
