name: Deploy to portainer

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    name: Deploy to portainer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Create / update
      - uses: rrennoir/portainer-stack@main
        with:
          portainerUrl: ${{ secrets.PORTAINER_HOST}}
          portainerApiKey: ${{ secrets.PORTAINER_ACCES_TOKEN }}
          portainerEndpointId: 2
          stackName: "app-test-ga"
          stackType: 2
          composeFile: stack-definition.yml
          delete: false
          prune: false
          pullImage: false
          verifySSL: false
